### PR TITLE
PDF support

### PR DESCRIPTION
**Pull request by Pei116**
- add support for pdf items in gallery
- add title field to gallery items
- title view using footer view in demo project

### CODE REVIEW

**Comment by zhangao0086** [comment]
Hi @Pei116 Thanks for your PR!!!

Just only one thing: I think the `title` of `DKPhotoGalleryItem` is unnecessary, because it's not useful for `DKPhotoGallery`. You can make a class that inherits from `DKPhotoGalleryItem` and then add the `title` property.

**Comment by Pei116** [comment]
Maybe, I will revise PR to remove that as I agree on that it's not really needed at this point, hopefully within tomorrow.

**Comment by Pei116** [comment]
@zhangao0086 I've made changes accordingly.

**Comment by zhangao0086** [comment]
Merged! Thanks for your PR!!! :)

**Pull request merged**
